name: frontend_dh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_html: 3.0.0-beta.2
  flutter_math_fork: 0.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  url_launcher: ^6.0.9
  http: ^1.2.2
  cached_network_image: ^3.4.1
  flutter_naver_map: ^1.3.0+1
  kakao_map_plugin: ^0.3.2
  get_it: ^8.0.2
  flutter_bottom_drawer: ^0.1.0
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.0

flutter:

  uses-material-design: true



